name = "STAR web"
packages = []
[files]
"../gamesave.py" = "./gamesave.py"
"../decode.py" = "./decode.py"
"../encode.py" = "./encode.py"
"../enums.py" = "./enums.py"
"../gamesave-schema.json" = "./gamesave-schema.json"
